### ISSUE TITLE
Not working now??

### ISSUE THREAD

**Issue by dgbkn** [theabbie/seedr-api#18]

**Comment by theabbie** [comment]
@dgbkn It is working, try with different accounts maybe.

**Comment by dgbkn** [comment]
No I tried it response is 500 please check

**Comment by theabbie** [comment]
@dgbkn Yes, getting the same error, I hope it's temporary, if they changed the API, it will be difficult to fix it.

**Comment by dgbkn** [comment]
![Screenshot_20210702-231804](https://user-images.githubusercontent.com/65810521/124311722-cbbc8980-db8b-11eb-9e4f-21429ff6fc6b.jpg)

**Comment by dgbkn** [comment]
> @dgbkn Yes, getting the same error, I hope it's temporary, if they changed the API, it will be difficult to fix it.
Oh

**Comment by dgbkn** [comment]
That would be bad of them

**Comment by dgbkn** [comment]
https://www.seedr.cc/pulse/api-doc/
See sir if you are able to implement this

**Comment by dgbkn** [comment]
It is mentioned in official docs

**Comment by theabbie** [comment]
@dgbkn It's for premium users only, this is not a big deal, I took it from their chrome extension, and their chrome extension is also not working, they will have to fix this, if they change it, I will take it again from the chrome extension.

**Comment by dgbkn** [comment]
Oh then they will need to fix it 😂

**Comment by dgbkn** [comment]
Any updates?

**Comment by theabbie** [comment]
@dgbkn Not fixed yet, I don't think it will be fixed soon, you can check their chrome extension, once that starts working, I will fix this.

**Comment by dgbkn** [comment]
now have they fixed it

**Comment by theabbie** [comment]
@dgbkn No, you can check their chrome extension, if that starts working, let me know.

**Comment by dgbkn** [comment]
@theabbie  ok i will keep checking it

**Comment by dgbkn** [comment]
https://chrome.google.com/webstore/detail/sonicbit/caeebcagcpmjhlmndepapcokebchemij
@theabbie I found alternative to seedr please add it's api also if possible please

**Comment by theabbie** [comment]
@dgbkn Sure, will do

**Comment by dgbkn** [comment]
Ok thanks 😌 glad to hear that

**Comment by theabbie** [comment]
@dgbkn Good news, they fixed it, it's working now.

**Comment by dgbkn** [comment]
Oh its good :)
